# f = open("test.txt",encoding="utf8")
# f_ = open("new.txt","w",encoding="utf8")
# lines = f.read().strip().split("\n")
# for line in lines:
#     # char_error = []
#     # id = []
#     pairs = line.split("/")
#     pairs[0]=pairs[0].replace("Ａ","a")
#     pairs[0]=pairs[0].replace("Ｂ","b")
#     pairs[0]=pairs[0].replace("Ｃ","c")
#     pairs[0]=pairs[0].replace("Ｄ","d")
#     pairs[0]=pairs[0].replace("Ｅ","e")
#     pairs[0]=pairs[0].replace("ｆ","f")
#     pairs[0]=pairs[0].replace("ｇ","g")
#     pairs[0]=pairs[0].replace("ｈ","h")
#     pairs[0]=pairs[0].replace("Ｉ","i")
#     pairs[0]=pairs[0].replace("ｊ","j")
#     pairs[0]=pairs[0].replace("ｋ","k")
#     pairs[0]=pairs[0].replace("Ｌ","l")
#     pairs[0]=pairs[0].replace("ｍ","m")
#     pairs[0]=pairs[0].replace("ｎ","n")
#     pairs[0]=pairs[0].replace("Ｏ","o")
#     pairs[0]=pairs[0].replace("ｐ","p")
#     pairs[0]=pairs[0].replace("Ｑ","q")
#     pairs[0]=pairs[0].replace("ｒ","r")
#     pairs[0]=pairs[0].replace("Ｓ","s")
#     pairs[0]=pairs[0].replace("ｔ","t")
#     pairs[0]=pairs[0].replace("ｕ","u")
#     pairs[0]=pairs[0].replace("ｖ","v")
#     pairs[0]=pairs[0].replace("Ｗ","w")
#     pairs[0]=pairs[0].replace("ｘ","x")
#     pairs[0]=pairs[0].replace("ｙ","y")
#     pairs[0]=pairs[0].replace("ｚ","z")
#     pairs[1]=pairs[1].replace("Ａ","a")
#     pairs[1]=pairs[1].replace("Ｂ","b")
#     pairs[1]=pairs[1].replace("Ｃ","c")
#     pairs[1]=pairs[1].replace("Ｄ","d")
#     pairs[1]=pairs[1].replace("Ｅ","e")
#     pairs[1]=pairs[1].replace("ｆ","f")
#     pairs[1]=pairs[1].replace("ｇ","g")
#     pairs[1]=pairs[1].replace("ｈ","h")
#     pairs[1]=pairs[1].replace("Ｉ","i")
#     pairs[1]=pairs[1].replace("ｊ","j")
#     pairs[1]=pairs[1].replace("ｋ","k")
#     pairs[1]=pairs[1].replace("Ｌ","l")
#     pairs[1]=pairs[1].replace("ｍ","m")
#     pairs[1]=pairs[1].replace("ｎ","n")
#     pairs[1]=pairs[1].replace("Ｏ","o")
#     pairs[1]=pairs[1].replace("ｐ","p")
#     pairs[1]=pairs[1].replace("Ｑ","q")
#     pairs[1]=pairs[1].replace("ｒ","r")
#     pairs[1]=pairs[1].replace("Ｓ","s")
#     pairs[1]=pairs[1].replace("ｔ","t")
#     pairs[1]=pairs[1].replace("ｕ","u")
#     pairs[1]=pairs[1].replace("ｖ","v")
#     pairs[1]=pairs[1].replace("Ｗ","w")
#     pairs[1]=pairs[1].replace("ｘ","x")
#     pairs[1]=pairs[1].replace("ｙ","y")
#     pairs[1]=pairs[1].replace("ｚ","z")

#     f_.writelines(pairs[0]+'/'+pairs[1]+"/"+pairs[2]+'/'+pairs[3]+'/'+pairs[4]+'/'+pairs[5]+"\n")
# import pickle
# of = open("new_train.txt","w",encoding="utf8")
# with open("trainall.times2.pkl", mode='rb') as f:
#     data_list = pickle.load(f)
# for data in data_list:
#     of.writelines(data["src"]+"/"+data["tgt"]+"\n")
f = open("new_test.txt",encoding="utf8")
f_ = open("test_.txt","w",encoding="utf8")
lines = f.read().strip().split("\n")
for line in lines:
    char_error = []
    id = []
    pairs = line.split("/")
    src = pairs[0]
    tgt = pairs[1]
    for i in range(len(src)):
        if src[i]!=tgt[i]:
            id.append(i)
            char_error.append((i,tgt[i]))
    f_.writelines(src+"/"+tgt+"/"+str(char_error)+"/"+str(id)+"\n")